[package]
name = "oprf"
type = "lib"
authors = [""]

[dependencies]
babyjubjub = { path = "../babyjubjub" }
poseidon2 = { tag = "v0.5.0-beta.0", git = "https://github.com/TaceoLabs/noir-poseidon", directory = "poseidon2" }
