beta = "63865932500786004558985758765891911620034145599124743624338496685411118977"
dlog_e = "21651611782908870028415356680205912578677611779857889287526859934595727462023"
dlog_s = "813348544856521250944635798658236115440111721634739064595636884345549099749"
commitment = "0x13e75fabe371ba4c0ad318cfde3eaac9185d8ad2ce743ea71e038b23abfb7d08"
preimage = "42"

[oprf_pk]
x = "5710999305174746446129006558187982651929018212457711080538180123406991257834"
y = "14822830093014637273720066510303560520096190665043878041612158237057634974510"

[oprf_response]
x = "8239981253288452954319423631647803967161484725248664916163883751103616749641"
y = "10909431257409573621736924846505941126161080693380329853422959666368005023270"

[oprf_response_blinded]
x = "3155679112931956901250628220045483261937665592711481372076828199008185725288"
y = "2295756075485931574186491588789693245723103184777309603040062940469350270432"
