name: Noir Tests and Formatting

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: 1.0.0-beta.18
      - run: cd babyjubjub && nargo test
      - run: cd oprf && nargo test
      - run: cd oprf_example && nargo test

  fmt:
    name: nargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: 1.0.0-beta.18
      - run: cd babyjubjub && nargo fmt --check
      - run: cd oprf && nargo fmt --check
      - run: cd oprf_example && nargo fmt --check
